name: readmit_pred
channels:
  - conda-forge
  - pytorch
  - defaults

dependencies:
  # Core Python
  - python=3.11
  
  # Scientific computing (with compatible versions)
  - numpy=1.24.3
  - scipy=1.11.3
  - pandas=2.1.4
  
  # Machine learning
  - scikit-learn=1.3.2
  
  # Visualization
  - matplotlib=3.8.0
  - seaborn=0.13.0
  - plotly=5.17.0
  
  # Deep learning (CPU version for better compatibility)
  - pytorch=2.1.0
  - torchvision=0.16.0
  - cpuonly
  
  # Utilities
  - pyyaml=6.0.1
  - tqdm=4.66.1
  
  # Jupyter (optional)
  - jupyter=1.0.0
  - ipykernel=6.26.0
  
  # Install via pip (not available in conda or need specific versions)
  - pip
  - pip:
    - xgboost==2.0.3
    - statsmodels==0.14.0
    - imbalanced-learn==0.11.0
    - shap==0.43.0
    - lifelines==0.27.8
